name: Hlint

on:
  pull_request:
    paths:
      - "**.hs"
      - .github/workflows/hlint.yaml
  push:
    paths:
      - "**.hs"
      - .github/workflows/hlint.yaml
    branches:
      - master

concurrency:
  group: hpqtypes-extras-hlint-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  hlint:
    runs-on:
      - ubuntu-22.04
    steps:
      # v3.5.3
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      # v2.4.6
      - uses: haskell/actions/hlint-setup@a99601b177e00b98c78b6f6de680a101cf1c619d
        with:
          version: 3.6.1
      # v2.4.6
      - uses: haskell/actions/hlint-run@a99601b177e00b98c78b6f6de680a101cf1c619d
        with:
          path: ./
          fail-on: warning
